# Generated by Django 4.2.7 on 2025-11-05 21:00

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='correo_institucional',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Institucional'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[core.models.validar_rut_chileno], verbose_name='RUT'),
        ),
    ]
