# Generated by Django 4.2.7 on 2025-11-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_apellido_usuario_correo_institucional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cambio_password_requerido',
            field=models.BooleanField(default=True, verbose_name='Cambio de Contraseña Requerido'),
        ),
    ]
