# Generated by Django 4.2.7 on 2025-11-06 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usuario_cambio_password_requerido'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='turno',
            field=models.CharField(blank=True, choices=[('apertura', 'Apertura (09:00 - 13:00)'), ('tarde', 'Tarde (13:00 - 17:00)'), ('cierre', 'Cierre (17:00 - 21:00)')], max_length=20, null=True, verbose_name='Turno'),
        ),
    ]
