# Generated by Django 4.2.7 on 2025-11-06 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_asistencia_turno'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroLlamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contador_llamada', models.IntegerField(unique=True, verbose_name='Contador de Llamada')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('motivo', models.CharField(max_length=200, verbose_name='Motivo de la Llamada')),
                ('tecnico_contactado', models.CharField(max_length=200, verbose_name='Técnico Contactado')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('resuelta', 'Resuelta'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
                ('usuario_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llamadas_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Registra')),
            ],
            options={
                'verbose_name': 'Registro de Llamada',
                'verbose_name_plural': 'Registros de Llamadas',
                'ordering': ['-fecha', '-contador_llamada'],
            },
        ),
        migrations.CreateModel(
            name='RegistroFalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contador_falla', models.IntegerField(unique=True, verbose_name='Contador de Falla')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('maquina', models.CharField(max_length=200, verbose_name='Máquina')),
                ('descripcion', models.TextField(verbose_name='Descripción de la Falla')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_reparacion', 'En Reparación'), ('resuelta', 'Resuelta')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
                ('usuario_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fallas_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Registra')),
            ],
            options={
                'verbose_name': 'Registro de Falla',
                'verbose_name_plural': 'Registros de Fallas',
                'ordering': ['-fecha', '-contador_falla'],
            },
        ),
    ]
