# Generated by Django 4.2.7 on 2025-11-06 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_registrollamada_registrofalla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrofalla',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='registrollamada',
            name='estado',
        ),
    ]
