# Generated by Django 4.2.7 on 2025-11-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_registrofalla_estado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventario',
            options={'ordering': ['categoria', 'nombre'], 'verbose_name': 'Producto de Inventario', 'verbose_name_plural': 'Productos de Inventario'},
        ),
        migrations.AddField(
            model_name='inventario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='inventario/', verbose_name='Imagen del Producto'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='cantidad',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='categoria',
            field=models.CharField(choices=[('bodega', 'Bodega'), ('meson', 'Mesón'), ('limpieza', 'Limpieza')], max_length=20, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre del Producto'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Unitario'),
        ),
        migrations.AlterField(
            model_name='registrofalla',
            name='maquina',
            field=models.CharField(max_length=200, verbose_name='Código de Máquina'),
        ),
    ]
