# Generated by Django 4.2.7 on 2025-11-06 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_pedido_detallepedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('login', 'Inicio de Sesión'), ('logout', 'Cierre de Sesión'), ('login_failed', 'Intento de Login Fallido'), ('password_change', 'Cambio de Contraseña'), ('usuario_create', 'Creación de Usuario'), ('usuario_edit', 'Edición de Usuario'), ('usuario_delete', 'Eliminación de Usuario'), ('usuario_activate', 'Activación de Usuario'), ('usuario_deactivate', 'Desactivación de Usuario'), ('inventario_create', 'Creación de Producto'), ('inventario_edit', 'Edición de Producto'), ('inventario_delete', 'Eliminación de Producto'), ('inventario_stock_change', 'Cambio de Stock'), ('asistencia_create', 'Registro de Asistencia'), ('asistencia_edit', 'Edición de Asistencia'), ('asistencia_delete', 'Eliminación de Asistencia'), ('pedido_create', 'Creación de Pedido'), ('pedido_delete', 'Eliminación de Pedido'), ('pedido_export', 'Exportación de Pedido'), ('falla_create', 'Registro de Falla'), ('falla_edit', 'Edición de Falla'), ('falla_delete', 'Eliminación de Falla'), ('llamada_create', 'Registro de Llamada'), ('llamada_edit', 'Edición de Llamada'), ('llamada_delete', 'Eliminación de Llamada')], max_length=50, verbose_name='Acción')),
                ('modulo', models.CharField(choices=[('sesion', 'Sesión'), ('usuarios', 'Usuarios'), ('inventario', 'Inventario'), ('asistencia', 'Asistencia'), ('pedidos', 'Ventas y Pedidos'), ('operaciones', 'Operaciones')], max_length=50, verbose_name='Módulo')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('detalles', models.TextField(blank=True, null=True, verbose_name='Detalles Adicionales (JSON)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora')),
                ('objeto_afectado', models.CharField(blank=True, max_length=200, null=True, verbose_name='Objeto Afectado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['-fecha_hora'], name='core_audito_fecha_h_be55f8_idx'), models.Index(fields=['usuario'], name='core_audito_usuario_581303_idx'), models.Index(fields=['modulo'], name='core_audito_modulo_2b8ded_idx'), models.Index(fields=['accion'], name='core_audito_accion_0ce1ff_idx')],
            },
        ),
    ]
