# Generated by Django 4.2.7 on 2025-11-06 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auditoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditoria',
            name='ip_address',
        ),
    ]
