# Generated by Django 4.2.7 on 2025-11-07 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_auditoria_ip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Evento')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha_evento', models.DateField(verbose_name='Fecha del Evento')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='eventos/', verbose_name='Imagen del Evento')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-fecha_evento', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ImagenCarrusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='carousel/', verbose_name='Imagen del Carrusel')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden de Visualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Imagen del Carrusel',
                'verbose_name_plural': 'Imágenes del Carrusel',
                'ordering': ['orden', 'fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la Noticia')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha_publicacion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Publicación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['-fecha_publicacion', '-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Unitario'),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='accion',
            field=models.CharField(choices=[('login', 'Inicio de Sesión'), ('logout', 'Cierre de Sesión'), ('login_failed', 'Intento de Login Fallido'), ('password_change', 'Cambio de Contraseña'), ('usuario_create', 'Creación de Usuario'), ('usuario_edit', 'Edición de Usuario'), ('usuario_delete', 'Eliminación de Usuario'), ('usuario_activate', 'Activación de Usuario'), ('usuario_deactivate', 'Desactivación de Usuario'), ('inventario_create', 'Creación de Producto'), ('inventario_edit', 'Edición de Producto'), ('inventario_delete', 'Eliminación de Producto'), ('inventario_stock_change', 'Cambio de Stock'), ('asistencia_create', 'Registro de Asistencia'), ('asistencia_edit', 'Edición de Asistencia'), ('asistencia_delete', 'Eliminación de Asistencia'), ('pedido_create', 'Creación de Pedido'), ('pedido_delete', 'Eliminación de Pedido'), ('pedido_export', 'Exportación de Pedido'), ('carrusel_create', 'Creación de Imagen Carrusel'), ('carrusel_edit', 'Edición de Imagen Carrusel'), ('carrusel_delete', 'Eliminación de Imagen Carrusel'), ('evento_create', 'Creación de Evento'), ('evento_edit', 'Edición de Evento'), ('evento_delete', 'Eliminación de Evento'), ('noticia_create', 'Creación de Noticia'), ('noticia_edit', 'Edición de Noticia'), ('noticia_delete', 'Eliminación de Noticia'), ('falla_create', 'Registro de Falla'), ('falla_edit', 'Edición de Falla'), ('falla_delete', 'Eliminación de Falla'), ('llamada_create', 'Registro de Llamada'), ('llamada_edit', 'Edición de Llamada'), ('llamada_delete', 'Eliminación de Llamada')], max_length=50, verbose_name='Acción'),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='modulo',
            field=models.CharField(choices=[('sesion', 'Sesión'), ('usuarios', 'Usuarios'), ('inventario', 'Inventario'), ('asistencia', 'Asistencia'), ('pedidos', 'Ventas y Pedidos'), ('operaciones', 'Operaciones'), ('contenido', 'Contenido')], max_length=50, verbose_name='Módulo'),
        ),
    ]
