# Generated by Django 4.2.7 on 2025-11-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_evento_imagencarrusel_noticia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='noticias/', verbose_name='Imagen de la Noticia'),
        ),
    ]
