# Generated by Django 4.2.7 on 2025-11-07 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_noticia_imagen'),
    ]

    operations = [
    ]
