# Generated by Django 4.2.7 on 2025-11-07 19:28

from django.db import migrations, models


def copy_nombre_to_codigo(apps, schema_editor):
    """Copiar datos de nombre a codigo antes de eliminar nombre"""
    Pedido = apps.get_model('core', 'Pedido')
    for pedido in Pedido.objects.all():
        if hasattr(pedido, 'nombre') and pedido.nombre:
            pedido.codigo = pedido.nombre
            pedido.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_pedido_nombre_to_codigo'),
    ]

    operations = [
        # Primero agregar el campo codigo (nullable)
        migrations.AddField(
            model_name='pedido',
            name='codigo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Código del Pedido'),
        ),
        # Copiar datos de nombre a codigo
        migrations.RunPython(copy_nombre_to_codigo, migrations.RunPython.noop),
        # Eliminar el campo nombre
        migrations.RemoveField(
            model_name='pedido',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='accion',
            field=models.CharField(choices=[('login', 'Inicio de Sesión'), ('logout', 'Cierre de Sesión'), ('login_failed', 'Intento de Login Fallido'), ('password_change', 'Cambio de Contraseña'), ('password_reset_request', 'Solicitud de Restablecimiento de Contraseña'), ('password_reset_admin', 'Restablecimiento de Contraseña por Admin'), ('usuario_create', 'Creación de Usuario'), ('usuario_edit', 'Edición de Usuario'), ('usuario_delete', 'Eliminación de Usuario'), ('usuario_activate', 'Activación de Usuario'), ('usuario_deactivate', 'Desactivación de Usuario'), ('inventario_create', 'Creación de Producto'), ('inventario_edit', 'Edición de Producto'), ('inventario_delete', 'Eliminación de Producto'), ('inventario_stock_change', 'Cambio de Stock'), ('asistencia_create', 'Registro de Asistencia'), ('asistencia_edit', 'Edición de Asistencia'), ('asistencia_delete', 'Eliminación de Asistencia'), ('pedido_create', 'Creación de Pedido'), ('pedido_delete', 'Eliminación de Pedido'), ('pedido_export', 'Exportación de Pedido'), ('carrusel_create', 'Creación de Imagen Carrusel'), ('carrusel_edit', 'Edición de Imagen Carrusel'), ('carrusel_delete', 'Eliminación de Imagen Carrusel'), ('evento_create', 'Creación de Evento'), ('evento_edit', 'Edición de Evento'), ('evento_delete', 'Eliminación de Evento'), ('noticia_create', 'Creación de Noticia'), ('noticia_edit', 'Edición de Noticia'), ('noticia_delete', 'Eliminación de Noticia'), ('falla_create', 'Registro de Falla'), ('falla_edit', 'Edición de Falla'), ('falla_delete', 'Eliminación de Falla'), ('llamada_create', 'Registro de Llamada'), ('llamada_edit', 'Edición de Llamada'), ('llamada_delete', 'Eliminación de Llamada')], max_length=50, verbose_name='Acción'),
        ),
    ]
