# Generated by Django 4.2.7 on 2025-11-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_contacto_manualinterno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manualinterno',
            options={'ordering': ['-fecha_actualizacion'], 'verbose_name': 'Documentación', 'verbose_name_plural': 'Documentación'},
        ),
        migrations.AddField(
            model_name='manualinterno',
            name='tipo',
            field=models.CharField(choices=[('reglamento', 'Reglamento Interno'), ('operaciones', 'Manual de Operaciones')], default='reglamento', max_length=20, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='manualinterno',
            name='archivo',
            field=models.FileField(upload_to='manuales/', verbose_name='Archivo del Documento'),
        ),
        migrations.AlterField(
            model_name='manualinterno',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título del Documento'),
        ),
    ]
