# Generated by Django 4.2.7 on 2025-11-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_manualinterno_options_manualinterno_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagencarrusel',
            name='titulo_barista',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Título/Nombre del Barista del Mes (solo para orden 1)'),
        ),
    ]
