# Generated by Django 4.2.7 on 2025-11-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_imagencarrusel_titulo_barista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='accion',
            field=models.CharField(choices=[('login', 'Inicio de Sesión'), ('logout', 'Cierre de Sesión'), ('login_failed', 'Intento de Login Fallido'), ('password_change', 'Cambio de Contraseña'), ('password_reset_request', 'Solicitud de Restablecimiento de Contraseña'), ('password_reset_admin', 'Restablecimiento de Contraseña por Admin'), ('usuario_create', 'Creación de Usuario'), ('usuario_edit', 'Edición de Usuario'), ('usuario_delete', 'Eliminación de Usuario'), ('usuario_activate', 'Activación de Usuario'), ('usuario_deactivate', 'Desactivación de Usuario'), ('inventario_create', 'Creación de Producto'), ('inventario_edit', 'Edición de Producto'), ('inventario_delete', 'Eliminación de Producto'), ('inventario_stock_change', 'Cambio de Stock'), ('asistencia_create', 'Registro de Asistencia'), ('asistencia_edit', 'Edición de Asistencia'), ('asistencia_delete', 'Eliminación de Asistencia'), ('pedido_create', 'Creación de Pedido'), ('pedido_delete', 'Eliminación de Pedido'), ('pedido_export', 'Exportación de Pedido'), ('carrusel_create', 'Creación de Imagen Carrusel'), ('carrusel_edit', 'Edición de Imagen Carrusel'), ('carrusel_delete', 'Eliminación de Imagen Carrusel'), ('evento_create', 'Creación de Evento'), ('evento_edit', 'Edición de Evento'), ('evento_delete', 'Eliminación de Evento'), ('noticia_create', 'Creación de Noticia'), ('noticia_edit', 'Edición de Noticia'), ('noticia_delete', 'Eliminación de Noticia'), ('falla_create', 'Registro de Falla'), ('falla_edit', 'Edición de Falla'), ('falla_delete', 'Eliminación de Falla'), ('llamada_create', 'Registro de Llamada'), ('llamada_edit', 'Edición de Llamada'), ('llamada_delete', 'Eliminación de Llamada'), ('contacto_create', 'Creación de Contacto'), ('contacto_edit', 'Edición de Contacto'), ('contacto_delete', 'Eliminación de Contacto')], max_length=50, verbose_name='Acción'),
        ),
    ]
