# Generated by Django 4.2.7 on 2025-11-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_auditoria_accion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='_es_administrador',
            field=models.BooleanField(db_column='es_administrador', default=False, verbose_name='Es Administrador'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='es_empleado',
            field=models.BooleanField(default=True, verbose_name='Es Empleado'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Rol (deprecated)'),
        ),
    ]
