# Generated by Django 4.2.7 on 2025-11-18 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_multiple_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='es_empleado',
            new_name='es_colaborador',
        ),
    ]
