from django.urls import path
from . import views

urlpatterns = [
    path('', views.index_view, name='index'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('olvidaste-contraseña/', views.solicitar_restablecimiento_password, name='solicitar_restablecimiento'),
    path('cambiar-password/', views.cambiar_password_view, name='cambiar_password'),
    path('panel/usuarios/restablecer-password/<int:usuario_id>/', views.restablecer_password_admin, name='restablecer_password_admin'),
    path('contactanos/', views.contactanos_view, name='contactanos'),
    path('documentacion/', views.documentacion_view, name='documentacion'),
    path('equipo/', views.equipo_view, name='equipo'),
    path('creditos/', views.creditos_view, name='creditos'),
    path('reglamento-interno/', views.reglamento_interno_view, name='reglamento_interno'),
    path('trabajador/dashboard/', views.trabajador_dashboard_view, name='trabajador_dashboard'),
    path('trabajador/registro-asistencia/', views.registro_asistencia_view, name='registro_asistencia'),
    path('trabajador/cambiar-stock/', views.cambiar_stock_view, name='cambiar_stock'),
    path('trabajador/actualizar-stock/<int:producto_id>/', views.actualizar_stock_view, name='actualizar_stock'),
    path('panel/', views.panel_view, name='panel'),
    path('panel/usuarios/', views.usuarios_view, name='usuarios'),
    path('panel/usuarios/crear/', views.crear_usuario_view, name='crear_usuario'),
    path('panel/usuarios/editar/<int:usuario_id>/', views.editar_usuario_view, name='editar_usuario'),
    path('panel/usuarios/eliminar/<int:usuario_id>/', views.eliminar_usuario_view, name='eliminar_usuario'),
    path('panel/inventario/', views.inventario_view, name='inventario'),
    path('panel/inventario/crear/', views.crear_inventario_view, name='crear_inventario'),
    path('panel/inventario/editar/<int:producto_id>/', views.editar_inventario_view, name='editar_inventario'),
    path('panel/inventario/eliminar/<int:producto_id>/', views.eliminar_inventario_view, name='eliminar_inventario'),
    path('panel/asistencia/', views.asistencia_view, name='asistencia'),
    path('panel/productos/', views.productos_view, name='productos'),
    path('panel/productos/agregar-carrito/<int:producto_id>/', views.agregar_al_carrito_view, name='agregar_al_carrito'),
    path('panel/productos/carrito/', views.ver_carrito_view, name='ver_carrito'),
    path('panel/productos/carrito/eliminar/<int:producto_id>/', views.eliminar_del_carrito_view, name='eliminar_del_carrito'),
    path('panel/productos/carrito/modificar/<int:producto_id>/', views.modificar_cantidad_carrito_view, name='modificar_cantidad_carrito'),
    path('panel/productos/pedidos/', views.pedidos_view, name='pedidos'),
    path('panel/productos/crear/', views.crear_pedido_view, name='crear_pedido'),
    path('panel/productos/pedidos/exportar/<int:pedido_id>/', views.exportar_pedido_excel, name='exportar_pedido_excel'),
    path('panel/productos/pedidos/eliminar/<int:pedido_id>/', views.eliminar_pedido_view, name='eliminar_pedido'),
    path('panel/productos/editar-precio/<int:producto_id>/', views.editar_precio_producto_view, name='editar_precio_producto'),
    path('panel/deliverys/', views.deliverys_view, name='deliverys'),
    path('panel/operaciones/', views.operaciones_view, name='operaciones'),
    path('panel/operaciones/fallas/crear/', views.crear_falla_view, name='crear_falla'),
    path('panel/operaciones/fallas/editar/<int:falla_id>/', views.editar_falla_view, name='editar_falla'),
    path('panel/operaciones/fallas/eliminar/<int:falla_id>/', views.eliminar_falla_view, name='eliminar_falla'),
    path('panel/operaciones/llamadas/crear/', views.crear_llamada_view, name='crear_llamada'),
    path('panel/operaciones/llamadas/editar/<int:llamada_id>/', views.editar_llamada_view, name='editar_llamada'),
    path('panel/operaciones/llamadas/eliminar/<int:llamada_id>/', views.eliminar_llamada_view, name='eliminar_llamada'),
    path('panel/asistencia/editar/<int:asistencia_id>/', views.editar_asistencia_view, name='editar_asistencia'),
    path('panel/asistencia/eliminar/<int:asistencia_id>/', views.eliminar_asistencia_view, name='eliminar_asistencia'),
    path('panel/auditoria/', views.auditoria_view, name='auditoria'),
    # Gestión de Contenido
    path('panel/carrusel/', views.gestionar_carrusel_view, name='gestionar_carrusel'),
    path('panel/carrusel/crear/', views.crear_imagen_carrusel_view, name='crear_imagen_carrusel'),
    path('panel/carrusel/editar/<int:imagen_id>/', views.editar_imagen_carrusel_view, name='editar_imagen_carrusel'),
    path('panel/carrusel/eliminar/<int:imagen_id>/', views.eliminar_imagen_carrusel_view, name='eliminar_imagen_carrusel'),
    path('panel/eventos/', views.gestionar_eventos_view, name='gestionar_eventos'),
    path('panel/eventos/crear/', views.crear_evento_view, name='crear_evento'),
    path('panel/eventos/editar/<int:evento_id>/', views.editar_evento_view, name='editar_evento'),
    path('panel/eventos/eliminar/<int:evento_id>/', views.eliminar_evento_view, name='eliminar_evento'),
    path('panel/noticias/', views.gestionar_noticias_view, name='gestionar_noticias'),
    path('panel/noticias/crear/', views.crear_noticia_view, name='crear_noticia'),
    path('panel/noticias/editar/<int:noticia_id>/', views.editar_noticia_view, name='editar_noticia'),
    path('panel/noticias/eliminar/<int:noticia_id>/', views.eliminar_noticia_view, name='eliminar_noticia'),
    path('panel/contenido/contactos/', views.gestionar_contactos_view, name='gestionar_contactos'),
    path('panel/contenido/contactos/crear/', views.crear_contacto_view, name='crear_contacto'),
    path('panel/contenido/contactos/editar/<int:contacto_id>/', views.editar_contacto_view, name='editar_contacto'),
    path('panel/contenido/contactos/eliminar/<int:contacto_id>/', views.eliminar_contacto_view, name='eliminar_contacto'),
    path('panel/contenido/manual-interno/', views.gestionar_manual_interno_view, name='gestionar_manual_interno'),
    path('panel/contenido/manual-interno/crear/', views.crear_manual_interno_view, name='crear_manual_interno'),
    path('panel/contenido/manual-interno/editar/<int:manual_id>/', views.editar_manual_interno_view, name='editar_manual_interno'),
    path('panel/contenido/manual-interno/eliminar/<int:manual_id>/', views.eliminar_manual_interno_view, name='eliminar_manual_interno'),
]



